basePath: /api/v1
definitions:
  common.RequestForgotPassword:
    properties:
      email:
        type: string
    required:
    - email
    type: object
  common.RequestLogin:
    properties:
      email:
        type: string
      password:
        maxLength: 100
        minLength: 8
        type: string
    required:
    - email
    - password
    type: object
  common.RequestOTP:
    properties:
      email:
        type: string
      otp:
        type: string
    required:
    - email
    - otp
    type: object
  common.ResponseError:
    properties:
      error:
        type: string
    type: object
  common.ResponseLogin:
    properties:
      access_token:
        type: string
      refresh_token:
        type: string
      role:
        type: string
      user_id:
        type: string
    type: object
  common.ResponseNormal:
    properties:
      data: {}
      email:
        type: string
      message:
        type: string
      result:
        type: boolean
    type: object
  models.Account:
    properties:
      account_status:
        type: boolean
      created_at:
        type: string
      email:
        type: string
      id:
        type: string
      is_verified:
        type: boolean
      password:
        maxLength: 100
        minLength: 8
        type: string
      role:
        type: string
    required:
    - email
    - password
    type: object
host: 127.0.0.1:9000
info:
  contact: {}
  description: List APIs of Healthy Management Service
  termsOfService: http://swagger.io/terms/
  title: Healthy Service API Document
  version: "1.0"
paths:
  /auth/change-password:
    post:
      consumes:
      - application/json
      description: Change password for the logged-in user
      parameters:
      - description: Change password request information
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/common.RequestLogin'
      produces:
      - application/json
      responses:
        "200":
          description: Password changed successfully
          schema:
            allOf:
            - $ref: '#/definitions/common.ResponseNormal'
            - properties:
                result:
                  type: boolean
              type: object
        "400":
          description: Invalid request body
          schema:
            $ref: '#/definitions/common.ResponseError'
        "401":
          description: Token must be in Bearer format
          schema:
            $ref: '#/definitions/common.ResponseError'
        "403":
          description: You do not have permission to access this resource
          schema:
            $ref: '#/definitions/common.ResponseError'
        "500":
          description: Internal server error
          schema:
            $ref: '#/definitions/common.ResponseError'
      security:
      - BearerAuth: []
      summary: Change password
      tags:
      - Auth
  /auth/forgot-password:
    post:
      consumes:
      - application/json
      description: Handle forgot password request
      parameters:
      - description: Forgot password request information
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/common.RequestForgotPassword'
      produces:
      - application/json
      responses:
        "200":
          description: OTP sent successfully
          schema:
            $ref: '#/definitions/common.ResponseNormal'
        "400":
          description: Invalid request body
          schema:
            $ref: '#/definitions/common.ResponseError'
        "500":
          description: Internal server error
          schema:
            $ref: '#/definitions/common.ResponseError'
      summary: Forgot password
      tags:
      - Auth
  /auth/login:
    post:
      consumes:
      - application/json
      description: Login to the system with email and password
      parameters:
      - description: Login request information
        in: body
        name: loginRequest
        required: true
        schema:
          $ref: '#/definitions/common.RequestLogin'
      produces:
      - application/json
      responses:
        "200":
          description: Login successful
          schema:
            $ref: '#/definitions/common.ResponseLogin'
        "400":
          description: Invalid request body
          schema:
            $ref: '#/definitions/common.ResponseError'
        "500":
          description: Internal server error
          schema:
            $ref: '#/definitions/common.ResponseError'
      summary: Login to the system
      tags:
      - Auth
  /auth/register:
    post:
      consumes:
      - application/json
      description: Register a new account with email and password
      parameters:
      - description: Account information
        in: body
        name: account
        required: true
        schema:
          $ref: '#/definitions/models.Account'
      produces:
      - application/json
      responses:
        "201":
          description: Account created successfully
          schema:
            allOf:
            - $ref: '#/definitions/common.ResponseNormal'
            - properties:
                email:
                  type: string
              type: object
        "400":
          description: Invalid request body
          schema:
            $ref: '#/definitions/common.ResponseError'
        "500":
          description: Internal server error
          schema:
            $ref: '#/definitions/common.ResponseError'
      summary: Register a new account
      tags:
      - Auth
  /auth/reset-password:
    post:
      consumes:
      - application/json
      description: Reset password after verifying OTP
      parameters:
      - description: Reset password request information
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/common.RequestLogin'
      produces:
      - application/json
      responses:
        "200":
          description: Password reset successfully
          schema:
            $ref: '#/definitions/common.ResponseNormal'
        "400":
          description: Invalid request body
          schema:
            $ref: '#/definitions/common.ResponseError'
        "500":
          description: Internal server error
          schema:
            $ref: '#/definitions/common.ResponseError'
      summary: Reset password
      tags:
      - Auth
  /auth/verify-email:
    post:
      consumes:
      - application/json
      description: Verify OTP for account registration or password reset
      parameters:
      - description: Request OTP information
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/common.RequestOTP'
      produces:
      - application/json
      responses:
        "200":
          description: OTP verified successfully
          schema:
            allOf:
            - $ref: '#/definitions/common.ResponseNormal'
            - properties:
                result:
                  type: boolean
              type: object
        "400":
          description: Invalid request parameters
          schema:
            $ref: '#/definitions/common.ResponseError'
        "500":
          description: Internal server error
          schema:
            $ref: '#/definitions/common.ResponseError'
      summary: Verify OTP for account
      tags:
      - Auth
  /auth/verify-otp:
    post:
      consumes:
      - application/json
      description: Verify OTP for forgot password
      parameters:
      - description: Request OTP information
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/common.RequestOTP'
      produces:
      - application/json
      responses:
        "200":
          description: OTP verified successfully
          schema:
            allOf:
            - $ref: '#/definitions/common.ResponseNormal'
            - properties:
                result:
                  type: boolean
              type: object
        "400":
          description: Invalid request parameters
          schema:
            $ref: '#/definitions/common.ResponseError'
        "500":
          description: Internal server error
          schema:
            $ref: '#/definitions/common.ResponseError'
      summary: Verify OTP for forgot password
      tags:
      - Auth
schemes:
- http
- https
swagger: "2.0"
